#!/usr/bin/env bash
#
# repo-map.sh — regenerate docs/REPO-MAP.md, the shared path & anchor map that
# both Cowork and Claude Code consult BEFORE giving or following any path-level
# instruction. Do NOT edit docs/REPO-MAP.md by hand — run this script.
#
# Output is deterministic (LC_ALL=C sort, day-granular UTC date) so two runs on
# the same day produce byte-identical files.
#
set -euo pipefail
export LC_ALL=C

cd "$(git rev-parse --show-toplevel)"

OUT="docs/REPO-MAP.md"
DATE="$(date -u +%Y-%m-%d)"

{
  echo "# REPO-MAP — tracked files & Markdown \`##\` anchors"
  echo
  echo "> **Generated by \`scripts/repo-map.sh\` — do not edit by hand.**"
  echo "> Regenerate whenever tracked files or headings change (UTC date: ${DATE})."
  echo ">"
  echo "> The shared map of paths + heading anchors. Cowork and Claude Code both consult"
  echo "> it before giving/following path-level instructions (see the governance-sync rule"
  echo "> in \`.claude/rules/\`). An instruction naming a path/anchor absent here → stop & report."
  echo
  echo "## Tracked files by directory"
  git ls-files | while IFS= read -r f; do
    d="${f%/*}"; [ "$d" = "$f" ] && d="(root)"
    printf '%s\t%s\n' "$d" "$f"
  done | sort | awk -F'\t' '
    $1 != prev { printf "\n### %s\n\n", $1; prev = $1 }
    { printf "- `%s`\n", $2 }
  '
  echo
  echo "## Markdown files — their \`##\`/\`###\` headings (anchors; code fences skipped)"
  git ls-files '*.md' | sort | while IFS= read -r md; do
    printf '\n### `%s`\n' "$md"
    # Only real headings: track ``` / ~~~ fences and ignore ## lines inside them,
    # so a heading shown in a code block is never mistaken for a navigable anchor.
    hs="$(awk '
      /^```/ { fence = !fence; next }
      /^~~~/ { fence = !fence; next }
      !fence && /^##+ / { print "  - " $0 }
    ' "$md")"
    if [ -n "$hs" ]; then printf '%s\n' "$hs"; else printf '  - _(no `##` headings — flat file)_\n'; fi
  done
} > "$OUT"

echo "wrote $OUT ($(git ls-files | wc -l | tr -d ' ') tracked files)"
